name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: pdo, pdo_mysql, yaml

      - name: Install dependencies
        run: composer install --no-interaction

      - name: Code style
        run: composer cs

      - name: Static analysis
        run: composer stan
